library(tidyverse)
h=head(diamonds)
s=str(diamonds)
g=glimpse(diamonds)
c=colnames(diamonds)
rename(diamonds,Colour=color,carat_new=carat)
summarize(diamonds,mean_carat = mean(carat))
summarize(diamonds,mode_table = mode(price))
summarize(diamonds,variance_x = var(x))
ggplot(data = diamonds, aes(x = carat, y = price)) +geom_point()
ggplot(data = diamonds, aes(x = carat, y = price, color = cut)) +geom_point()
ggplot(data = diamonds, aes(x = carat, y = price, color = cut)) +geom_point() +facet_wrap(~cut)
new_col=mutate(diamonds,carat_2=100*carat)
as_tibble(diamonds)
